Calculitar_Ultra/urls.py
from django.contrib import admin
from django.urls import path, include

api_routers = [
    path('v1/', include('count_api1.urls'))
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('api/', include(api_routers)),
]

count_api1/urls.py
from django.urls import path
from count_api1.views import add, subtract, multiply, divide

app_name = 'count_api1'

urlpatterns = [
    path('add/', add, name='add'),
    path('subtract/', subtract, name='subtract'),
    path('multiply/', multiply, name='multiply'),
    path('divide/', divide, name='divide'),
]

webapp/urls.py
from django.urls import path
from webapp.views import home

urlpatterns = [
    path('', home, name='home'),
]

count_api1/models.py
from django.db import models

# Create your models here.

webapp/models.py
from django.db import models

# Create your models here.

count_api1/views.py
import json
from django.http import JsonResponse
from django.views.decorators.csrf import ensure_csrf_cookie


@ensure_csrf_cookie
def calculitar(request, choose):
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            a = int(data.get("A"))
            b = int(data.get("B"))
            if choose == 'add':
                answer = a + b
            elif choose == 'subtract':
                answer = a - b
            elif choose == 'multiply':
                answer = a * b
            elif choose == 'divide':
                try:
                    answer = a / b
                except ZeroDivisionError:
                    return JsonResponse({'error': 'Division by zero error'}, status=400)
            else:
                return JsonResponse({'error': 'Something wrong'}, status=400)
            return JsonResponse({'answer': answer})
        except ValueError:
            return JsonResponse({'error': 'Wrong input'}, status=400)
        except ZeroDivisionError:
            return JsonResponse({'error': 'Division by zero'}, status=400)
    return JsonResponse({'error': 'Invalid request'}, status=400)


def add(request):
    return calculitar(request, 'add')


def subtract(request):
    return calculitar(request, 'subtract')


def multiply(request):
    return calculitar(request, 'multiply')


def divide(request):
    return calculitar(request, 'divide')

webapp/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

webapp/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Считаем</title>
</head>
<body>

<center><h1 style="margin-top: 100px">Делаем Подсчеты!</h1></center>

<center>
<span>Число А:</span>
<br>
<input type="text" placeholder="Считаем..." style="font-size: 15px; border: solid 2px; border-radius: 10px" id="a">
<br>
<br>
<span>Число B:</span>
<br>
<input type="text" placeholder="Считаем..." style="font-size: 15px; border: solid 2px; border-radius: 10px" id="b">
</center>

<center style="margin-top: 40px">
<a href="{% url 'count_api1:add' %}" style="text-decoration: none; color: black">add - сложить</a>
<br>
<br>
<a href="{% url 'count_api1:subtract' %}" style="text-decoration: none; color: black">subtract - вычесть</a>
<br>
<br>
<a href="{% url 'count_api1:divide' %}" style="text-decoration: none; color: black">divide - разделить</a>
<br>
<br>
<a href="{% url 'count_api1:multiply' %}" style="text-decoration: none; color: black">multiply - умножить</a>
</center>
<br>
<center>
    <div id="answer">
        
    </div>
</center>

<script src="{% static 'js/calculiruem.js' %}"></script>
</body>
</html>